### PR TITLE
fixed lost 'port' url part

### PR DESCRIPTION
**Pull request by brainm**

### CODE REVIEW

**Comment by aditi89** [comment]
i want to activate my university ldap profile in community server that i have installed on ubuntu 12.04 in local LAN.
despite the message "Activation link has been said to your email account" i have not received any mail regarding activation.

without activation i am not able to access any-features of community portal

any help will be appreciated.

**Comment by AnaMih** [comment]
Please, specify the following:
1) Version of OnlyOffice and the the download link 
2) Do you have a stable internet connection?
3) "university ldap profile" - does it mean that you import the profile from Ldap or it just your email.

**Comment by aditi89** [comment]
OnlyOffice -Version 8.6.0.24(have installed it without docker)
Yes,internet connection is very much stable.

its just my email.

**Comment by aditi89** [comment]
http://helpcenter.onlyoffice.com/server/linux/community/linux-installation.aspx

download link

**Comment by AnaMih** [comment]
Could you please follow the instructions given here http://www.noobslab.com/2015/03/onlyoffice-another-free-office-suite.html#comment-2343873456
Please let us know and send the requested log files.

**Comment by aditi89** [comment]
[mail.dog.sql.log.txt](https://github.com/ONLYOFFICE/CommunityServer/files/35190/mail.dog.sql.log.txt)
[nginx.access.log.txt](https://github.com/ONLYOFFICE/CommunityServer/files/35191/nginx.access.log.txt)
[svcNotify.11-16.log.txt](https://github.com/ONLYOFFICE/CommunityServer/files/35189/svcNotify.11-16.log.txt)


Please find attached requested log files.

**Comment by aditi89** [comment]
HI

I have again tried to re install onlyoffice.Now I am getting below issues
dpkg: error processing package onlyoffice-communityserver (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 onlyoffice-communityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)


what might be causing these error???

Any help??

**Comment by aditi89** [comment]
Hi!

I am still struck. I neither can send  test mails nor  able to connect via social media.In short nothing is going out of onlyoffice.

smtp ports are open.
I am using ubuntu 15.04
Can this be a issue of ssl certificate installation??

I work behind a proxy server.

And i dont know how to configure certificates for onlyoffice running on Ubuntu without docker.

Kindly help.

**Comment by DeanSp1** [comment]
In the logfiles we see that your server cannot connect to SMTP-server using the specified proxy. It means that configuration of proxy is incorrect or settings of the SMTP server are wrong.

2015-11-16 10:51:49,882 ERROR [NotifyThread 2015-11-16T05:21:49.8727910Z] ASC.Notify - Tenant: 0, To: aditi89.cstaff@iitd.ac.in - System.Net.Mail.SmtpException: Message could not be sent. ---> System.Net.Sockets.SocketException: Connection refused

**Pull request closed without merging**
